[phases.setup]
nixPkgs = ["python311", "gcc", "poppler_utils", "wkhtmltopdf"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn viewer_server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
